### ISSUE TITLE
Why didn't provide synchronized API?

### ISSUE THREAD

**Issue by jingedawang** [Cutano/Kawazu#17]

**Comment by ookii-tsuki** [comment]
I don't see the reason to run the method in the main thread as it is a little slow to tokenize the text especially when you have a large string, that would freeze your app, so it's better to run it in a separate thread. But in case that's what you want you can do that like this
```csharp
using var converter = new KawazuConverter();
var result = converter.Convert("今晩は").GetAwaiter().GetResult();
```

**Comment by jingedawang** [comment]
Sure, I agree. I just didn't know how to use GetAwaiter method before.
Thank you!
