### ISSUE TITLE
.net5 support request

### ISSUE THREAD

**Issue by VShawn** [Cutano/Kawazu#2]
![image](https://user-images.githubusercontent.com/10143738/110202017-1f9ab880-7ea1-11eb-8cdd-2b92fb50f3e3.png)

the current version Kawazu works only with .Net core1-3, I tested .Net5 and it works good only if I copy the `matrix.bin` and blabal files to the build output floder.

So it would be easy to support .Net5 by modify the csproj file.

---
BTW, it would helpful if you can support the old .net frameworks4+, there are a lot apps running on .net frameworks, but I'm not sure if Kawzu can run on .NetFramework4 without code changing, no test yet.

**Comment by Cutano** [comment]
OK, I will try to add support for .Net 5 and the older version, thx for the advice.

**Comment by Cutano** [comment]
Now you can use it on .Net 5, but it still not going to support .Net Frameworks due to the dependencies. However, it will work well on .Net Standard 2.0.
