### ISSUE TITLE
Dispose method to release unmanaged memory

### ISSUE THREAD

**Issue by med9999** [Cutano/Kawazu#3]
I think you should add a dispose method in the KawazuConverter class to dispose the MeCab tagger and release unmanaged memory because the garbage collector can't clean unmanaged memory.

**Comment by Cutano** [comment]
I see, I will try to fix that in the next update, thanks for the advice :)

**Comment by Cutano** [comment]
Problem solved!

**Comment by med9999** [comment]
Thanks
