### ISSUE TITLE
Question about Romaji

### ISSUE THREAD

**Issue by VShawn** [Cutano/Kawazu#6]
I don't know much about Japanese Romaji
But why it gets differet Romaji of `こんにちは` from google and Kawazu? Can I get the google's Romaji from Kawazu?

## Google

return `Kon'nichiwa`

![image](https://user-images.githubusercontent.com/10143738/110890478-125f4d00-832b-11eb-88d5-756cf1741a67.png)

## Kawazu
I tried different parameters of `Converter.GetDivisions` all return: `konnichiha`

**Comment by med9999** [comment]
You can try something like this:

```csharp
using NMeCab.Specialized;
```

```csharp
static string GetPronounciation(string word)
{
       using (var tagger = MeCabIpaDicTagger.Create())
       {
            var nodes = tagger.Parse(word);
            return nodes.First().Pronounciation;
       }
}
```
That'll return the word pronounciation in katakana, you can then convert to romaji using this method in the Utilities class
```csharp
string romaji = Utilities.ToRawRomaji(GetPronounciation("こんにちは"));
```
