### ISSUE TITLE
Furigana is sometimes inaccurate

### ISSUE THREAD

**Issue by hidemat** [Cutano/Kawazu#7]
Hi Cutano. I was playing around with the KawazuConverter and found that when converting to To.Hiragana in Mode.Furigana it sometimes returns inaccurate results. For example, with the word:

```
あの方
the result was: あのほう
and it should have been: あのかた
```

**Comment by Cutano** [comment]
This is because the sentence itself has more than one meaning. The character 方 means way when pronounced _hou_ , however, it means person when pronounced _kata_. As a result, Kawazu doesn't know which one is intended so the result is unexpected.

**Comment by med9999** [comment]
It's just how the IpaDic works, it is accurate most of the time but sometimes it can make mistakes, it's not the developer's fault
Even Google translate make mistakes like that too
Here I used your example:
![IMG_20210405_163302](https://user-images.githubusercontent.com/42550249/113592544-37469780-962d-11eb-85c3-dc6f800a353d.jpg)

**Comment by hidemat** [comment]
I see. I will try to find a work around for this and let you guys know if I find one. Thanks for replying.

**Comment by med9999** [comment]
> Is there a way to get a list of possible readings from a given kanji character?

I don't think you can do that with Kawazu but you can use [KanjiDic2](http://www.edrdg.org/wiki/index.php/KANJIDIC_Project) instead, it has a lot of useful information about each kanji including readings, radicals, meaning, etc...

**Comment by hidemat** [comment]
> I don't think you can do that with Kawazu but you can use [KanjiDic2](http://www.edrdg.org/wiki/index.php/KANJIDIC_Project) instead, it has a lot of useful information about each kanji including readings, radicals, meaning, etc...

Thanks.
